services:
  app:
    build: .
    container_name: go_app
    depends_on:
      - postgres
      - kafka
    environment:
      - DB_DRIVER_NAME=postgres
      - DB_SCHEME=user=user_db password=123 dbname=order_db sslmode=disable
      - KAFKA_BROKER=kafka:9092
      - KAFKA_TOPIC=orders
      - KAFKA_GROUP_ID=order_group
      - PORT=8080
    ports:
      - "8080:8080"
    networks:
      - app_network

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: user_db
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: order_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_network

  zookeeper:
    image: zookeeper:3.8.1
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - app_network

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - app_network
    depends_on:
      - zookeeper

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
